In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import dask.dataframe as dd

%matplotlib inline

In [6]:
df_2000 = dd.read_csv('2000.csv.bz2', compression = 'bz2', dtype={'CRSElapsedTime': 'float64'}, blocksize=None)

In [7]:
df_2000.head()

,Year,Month,DayofMonth,DayOfWeek,DepTime,CRSDepTime,ArrTime,CRSArrTime,UniqueCarrier,FlightNum,...,TaxiIn,TaxiOut,Cancelled,CancellationCode,Diverted,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay
0,2000,1,28,5,1647.0,1647,1906.0,1859,HP,154,...,15,11,0,NaN,0,NaN,NaN,NaN,NaN,NaN
1,2000,1,29,6,1648.0,1647,1939.0,1859,HP,154,...,5,47,0,NaN,0,NaN,NaN,NaN,NaN,NaN
2,2000,1,30,7,NaN,1647,NaN,1859,HP,154,...,0,0,1,NaN,0,NaN,NaN,NaN,NaN,NaN
3,2000,1,31,1,1645.0,1647,1852.0,1859,HP,154,...,7,14,0,NaN,0,NaN,NaN,NaN,NaN,NaN
4,2000,1,1,6,842.0,846,1057.0,1101,HP,609,...,3,8,0,NaN,0,NaN,NaN,NaN,NaN,NaN

In [8]:
df_2000.shape

(Delayed('int-4193eebc-f151-46a5-8e71-e6e47edd5f1a'), 29)

In [9]:
df_2000.info()

<class 'dask.dataframe.core.DataFrame'>
Columns: 29 entries, Year to LateAircraftDelay
dtypes: object(4), float64(13), int64(12)

In [10]:
df_2000.describe()

Dask DataFrame Structure:
                  Year    Month DayofMonth DayOfWeek  DepTime CRSDepTime  ArrTime CRSArrTime FlightNum ActualElapsedTime CRSElapsedTime  AirTime ArrDelay DepDelay Distance   TaxiIn  TaxiOut Cancelled CancellationCode Diverted CarrierDelay WeatherDelay NASDelay SecurityDelay LateAircraftDelay
npartitions=1
               float64  float64    float64   float64  float64    float64  float64    float64   float64           float64        float64  float64  float64  float64  float64  float64  float64   float64          float64  float64      float64      float64  float64       float64           float64
                   ...      ...        ...       ...      ...        ...      ...        ...       ...               ...            ...      ...      ...      ...      ...      ...      ...       ...              ...      ...          ...          ...      ...           ...               ...
Dask Name: describe-numeric, 120 tasks

In [14]:
df_2000_2008 = dd.read_csv('df_2000_2008.csv', dtype={'CancellationCode': 'object'})

In [19]:
df_2000_2008.tail(10)

,Year,Month,DayofMonth,DayOfWeek,DepTime,CRSDepTime,ArrTime,CRSArrTime,UniqueCarrier,FlightNum,...,TaxiIn,TaxiOut,Cancelled,CancellationCode,Diverted,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay
581541,2008,4,17,4,712.0,720,823.0,844,DL,1203,...,8.0,13.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN
581542,2008,4,17,4,934.0,940,1036.0,1050,DL,1203,...,4.0,16.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN
581543,2008,4,17,4,739.0,740,951.0,945,DL,1204,...,6.0,24.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN
581544,2008,4,17,4,601.0,600,823.0,819,DL,1205,...,8.0,28.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN
581545,2008,4,17,4,1047.0,1050,1248.0,1252,DL,1206,...,8.0,12.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN
581546,2008,4,17,4,1025.0,1025,1234.0,1237,DL,1207,...,5.0,16.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN
581547,2008,4,17,4,1319.0,1320,1527.0,1524,DL,1208,...,9.0,12.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN
581548,2008,4,17,4,1335.0,1335,1556.0,1553,DL,1209,...,7.0,31.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN
581549,2008,4,17,4,1933.0,1935,2140.0,2141,DL,1210,...,9.0,12.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN
581550,2008,4,17,4,621.0,615,752.0,754,DL,1211,...,15.0,12.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN

In [24]:
df_2000_2008.describe().compute()

,Year,Month,DayofMonth,DayOfWeek,DepTime,CRSDepTime,ArrTime,CRSArrTime,FlightNum,ActualElapsedTime,...,Distance,TaxiIn,TaxiOut,Cancelled,Diverted,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay
count,5.466495e+07,5.466495e+07,5.466495e+07,5.466495e+07,5.347104e+07,5.466495e+07,5.335730e+07,5.466495e+07,5.466495e+07,5.335730e+07,...,5.466495e+07,5.459485e+07,5.460050e+07,5.466495e+07,5.466495e+07,3.326538e+07,3.326538e+07,3.326538e+07,3.326538e+07,3.326538e+07
mean,2.003921e+03,6.325625e+00,1.572488e+01,3.940372e+00,1.344600e+03,1.337854e+03,1.492052e+03,1.501052e+03,1.854903e+03,1.255567e+02,...,7.296622e+02,6.894704e+00,1.557098e+01,2.184052e-02,2.080511e-03,3.340285e+00,7.229601e-01,3.716732e+00,2.543903e-02,4.307178e+00
std,2.392423e+00,3.453531e+00,8.783428e+00,1.990147e+00,4.771615e+02,4.655009e+02,5.016991e+02,4.825841e+02,1.762446e+03,7.081388e+01,...,5.703168e+02,2.897422e+01,1.164568e+01,1.461626e-01,4.556514e-02,1.886025e+01,8.965984e+00,1.573305e+01,1.167868e+00,1.919586e+01
min,2.000000e+03,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,0.000000e+00,1.000000e+00,0.000000e+00,1.000000e+00,-7.190000e+02,...,6.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,-6.000000e+01,0.000000e+00,0.000000e+00
25%,2.002000e+03,4.000000e+00,9.000000e+00,2.000000e+00,9.440000e+02,9.400000e+02,1.134000e+03,1.138000e+03,6.970000e+02,8.000000e+01,...,3.370000e+02,4.000000e+00,1.100000e+01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
50%,2.004000e+03,6.000000e+00,1.800000e+01,4.000000e+00,1.346000e+03,1.340000e+03,1.535000e+03,1.536000e+03,1.681000e+03,1.160000e+02,...,6.220000e+02,6.000000e+00,1.400000e+01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
75%,2.006000e+03,1.000000e+01,2.500000e+01,6.000000e+00,1.754000e+03,1.740000e+03,1.934000e+03,1.932000e+03,4.086000e+03,1.670000e+02,...,1.046000e+03,9.000000e+00,2.000000e+01,0.000000e+00,0.000000e+00,1.700000e+01,0.000000e+00,2.100000e+01,0.000000e+00,2.900000e+01
max,2.008000e+03,1.200000e+01,3.100000e+01,7.000000e+00,2.930000e+03,2.400000e+03,2.955000e+03,2.400000e+03,9.912000e+03,1.879000e+03,...,4.962000e+03,1.523000e+03,3.905000e+03,1.000000e+00,1.000000e+00,2.580000e+03,1.510000e+03,1.392000e+03,5.330000e+02,1.407000e+03

In [3]:
df_2001 = pd.read_csv('2001.csv.bz2', compression = 'bz2', encoding = 'latin-1')

In [4]:
df_2002 = pd.read_csv('2002.csv.bz2', compression = 'bz2', encoding = 'latin-1')

In [5]:
df_2003 = pd.read_csv('2003.csv.bz2', compression = 'bz2', low_memory=False)

In [6]:
df_2004 = pd.read_csv('2004.csv.bz2', compression = 'bz2', low_memory=False)

In [7]:
df_2005 = pd.read_csv('2005.csv.bz2', compression = 'bz2')

In [8]:
df_2006 = pd.read_csv('2006.csv.bz2', compression = 'bz2')

In [9]:
df_2007 = pd.read_csv('2007.csv.bz2', compression = 'bz2')

In [12]:
df_2007.shape

(7453215, 29)

In [10]:
df_2008 = pd.read_csv('2008.csv.bz2', compression = 'bz2')

In [11]:
df_2008.shape

(2389217, 29)

In [13]:
frames = [df_2000, df_2001, df_2002, df_2003, df_2004, df_2005, df_2006, df_2007, df_2008]

In [14]:
df_2000_2008 = pd.concat(frames)

In [15]:
df_2000_2008.shape

(54664946, 29)

In [20]:
df_2000_2008.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 54664946 entries, 0 to 2389216
Data columns (total 29 columns):
 #   Column             Dtype
---  ------             -----
 0   Year               int64
 1   Month              int64
 2   DayofMonth         int64
 3   DayOfWeek          int64
 4   DepTime            float64
 5   CRSDepTime         int64
 6   ArrTime            float64
 7   CRSArrTime         int64
 8   UniqueCarrier      object
 9   FlightNum          int64
 10  TailNum            object
 11  ActualElapsedTime  float64
 12  CRSElapsedTime     float64
 13  AirTime            float64
 14  ArrDelay           float64
 15  DepDelay           float64
 16  Origin             object
 17  Dest               object
 18  Distance           int64
 19  TaxiIn             float64
 20  TaxiOut            float64
 21  Cancelled          int64
 22  CancellationCode   object
 23  Diverted           int64
 24  CarrierDelay       float64
 25  WeatherDelay       float64
 26  NASDelay           float64
 27  SecurityDelay      float64
 28  LateAircraftDelay  float64
dtypes: float64(14), int64(10), object(5)
memory usage: 12.2+ GB

In [21]:
df_2000_2008.describe()

,Year,Month,DayofMonth,DayOfWeek,DepTime,CRSDepTime,ArrTime,CRSArrTime,FlightNum,ActualElapsedTime,...,Distance,TaxiIn,TaxiOut,Cancelled,Diverted,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay
count,5.466495e+07,5.466495e+07,5.466495e+07,5.466495e+07,5.347104e+07,5.466495e+07,5.335730e+07,5.466495e+07,5.466495e+07,5.335730e+07,...,5.466495e+07,5.459485e+07,5.460050e+07,5.466495e+07,5.466495e+07,3.326538e+07,3.326538e+07,3.326538e+07,3.326538e+07,3.326538e+07
mean,2.003921e+03,6.325625e+00,1.572488e+01,3.940372e+00,1.344600e+03,1.337854e+03,1.492052e+03,1.501052e+03,1.854903e+03,1.255567e+02,...,7.296622e+02,6.894704e+00,1.557098e+01,2.184052e-02,2.080511e-03,3.340285e+00,7.229601e-01,3.716732e+00,2.543903e-02,4.307178e+00
std,2.392423e+00,3.453531e+00,8.783428e+00,1.990147e+00,4.771615e+02,4.655009e+02,5.016991e+02,4.825841e+02,1.762446e+03,7.081388e+01,...,5.703168e+02,2.897422e+01,1.164568e+01,1.461626e-01,4.556514e-02,1.886025e+01,8.965984e+00,1.573305e+01,1.167868e+00,1.919586e+01
min,2.000000e+03,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,0.000000e+00,1.000000e+00,0.000000e+00,1.000000e+00,-7.190000e+02,...,6.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,-6.000000e+01,0.000000e+00,0.000000e+00
25%,2.002000e+03,3.000000e+00,8.000000e+00,2.000000e+00,9.320000e+02,9.300000e+02,1.114000e+03,1.120000e+03,5.500000e+02,7.400000e+01,...,3.180000e+02,4.000000e+00,1.000000e+01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
50%,2.004000e+03,6.000000e+00,1.600000e+01,4.000000e+00,1.331000e+03,1.327000e+03,1.520000e+03,1.525000e+03,1.264000e+03,1.070000e+02,...,5.750000e+02,5.000000e+00,1.300000e+01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
75%,2.006000e+03,9.000000e+00,2.300000e+01,6.000000e+00,1.735000e+03,1.725000e+03,1.916000e+03,1.913000e+03,2.476000e+03,1.570000e+02,...,9.640000e+02,8.000000e+00,1.800000e+01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
max,2.008000e+03,1.200000e+01,3.100000e+01,7.000000e+00,2.930000e+03,2.400000e+03,2.955000e+03,2.400000e+03,9.912000e+03,1.879000e+03,...,4.962000e+03,1.523000e+03,3.905000e+03,1.000000e+00,1.000000e+00,2.580000e+03,1.510000e+03,1.392000e+03,5.330000e+02,1.407000e+03

In [22]:
df_2000_2008.sample(50)

,Year,Month,DayofMonth,DayOfWeek,DepTime,CRSDepTime,ArrTime,CRSArrTime,UniqueCarrier,FlightNum,...,TaxiIn,TaxiOut,Cancelled,CancellationCode,Diverted,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay
4244626,2006,8,2,3,643.0,645,841.0,850,XE,2773,...,5.0,27.0,0,NaN,0,0.0,0.0,0.0,0.0,0.0
5190291,2000,11,13,1,1729.0,1730,2002.0,2000,DL,1993,...,8.0,29.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN
1562650,2002,4,4,4,1304.0,1310,1727.0,1734,DL,2216,...,6.0,29.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN
6311377,2003,12,25,4,NaN,1015,NaN,1450,HP,122,...,0.0,0.0,1,A,0,0.0,0.0,0.0,0.0,0.0
4676820,2002,11,1,5,831.0,830,849.0,850,DL,1715,...,5.0,27.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN
4672917,2004,8,26,4,1540.0,1530,1648.0,1632,CO,6,...,3.0,30.0,0,NaN,0,1.0,0.0,6.0,0.0,9.0
1677962,2002,4,15,1,854.0,900,1113.0,1114,AA,2965,...,6.0,35.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN
3579927,2001,7,14,6,2027.0,2030,2209.0,2209,AS,67,...,4.0,11.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN
5537745,2005,10,25,2,1542.0,1415,1648.0,1520,WN,2921,...,3.0,11.0,0,NaN,0,87.0,0.0,1.0,0.0,0.0
5144787,2001,11,27,2,1147.0,1140,1435.0,1444,US,2991,...,7.0,11.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN
5077775,2007,9,25,2,1155.0,1155,1411.0,1340,WN,2112,...,3.0,18.0,0,NaN,0,0.0,0.0,31.0,0.0,0.0
6658302,2007,11,19,1,1430.0,1430,1628.0,1638,NW,177,...,12.0,21.0,0,NaN,0,0.0,0.0,0.0,0.0,0.0
1578822,2001,4,14,6,1505.0,1445,1739.0,1724,US,2603,...,4.0,9.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN
2001329,2002,5,5,7,1613.0,1615,1734.0,1734,DL,1936,...,5.0,11.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN
3547308,2006,7,17,1,933.0,840,1051.0,955,WN,566,...,4.0,18.0,0,NaN,0,53.0,0.0,3.0,0.0,0.0
6193381,2006,11,26,7,658.0,700,1035.0,1034,UA,1518,...,7.0,12.0,0,NaN,0,0.0,0.0,0.0,0.0,0.0
2053481,2002,5,8,3,1359.0,1401,1549.0,1554,MQ,4339,...,2.0,10.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN
1727198,2005,3,2,3,801.0,800,1238.0,1249,DL,1157,...,9.0,10.0,0,NaN,0,0.0,0.0,0.0,0.0,0.0
9130,2007,1,4,4,1743.0,1735,1855.0,1840,WN,646,...,7.0,15.0,0,NaN,0,0.0,0.0,11.0,0.0,4.0
7160457,2007,12,27,4,1322.0,1320,1523.0,1520,DL,70,...,10.0,18.0,0,NaN,0,0.0,0.0,0.0,0.0,0.0
1506561,2008,3,1,6,1255.0,1300,1421.0,1434,EV,4343,...,5.0,13.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN
5586246,2007,9,3,1,1742.0,1745,1942.0,1950,DL,1635,...,12.0,15.0,0,NaN,0,0.0,0.0,0.0,0.0,0.0
257280,2007,1,15,1,1421.0,1320,1535.0,1444,UA,1195,...,5.0,8.0,0,NaN,0,0.0,0.0,0.0,0.0,51.0
2370082,2002,6,11,2,1433.0,1435,1611.0,1618,UA,1429,...,4.0,10.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN
964191,2000,3,15,3,856.0,905,1000.0,1003,DL,1487,...,5.0,25.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN
5113693,2006,9,19,2,1058.0,1100,1246.0,1255,MQ,3611,...,4.0,12.0,0,NaN,0,0.0,0.0,0.0,0.0,0.0
1574343,2004,3,16,2,654.0,655,817.0,830,MQ,4913,...,2.0,18.0,0,NaN,0,0.0,0.0,0.0,0.0,0.0
2343244,2008,4,3,4,643.0,645,922.0,920,CO,193,...,10.0,14.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN
6435532,2007,11,20,2,2106.0,2045,2200.0,2146,OO,3664,...,4.0,7.0,0,NaN,0,0.0,0.0,0.0,0.0,0.0
5207697,2001,11,6,2,1825.0,1825,1855.0,1910,WN,1857,...,2.0,5.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN
3461095,2005,6,18,6,1054.0,1102,1609.0,1605,AA,1556,...,24.0,12.0,0,NaN,0,0.0,0.0,0.0,0.0,0.0
660320,2008,2,19,2,2025.0,2030,2144.0,2150,WN,976,...,5.0,6.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN
4011817,2003,8,11,1,1210.0,1215,1454.0,1428,XE,2266,...,7.0,30.0,0,NaN,0,0.0,0.0,26.0,0.0,0.0
4869708,2000,11,3,5,1252.0,1230,1411.0,1352,US,867,...,3.0,28.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN
1522282,2000,4,28,5,1548.0,1540,1941.0,1908,TW,160,...,9.0,36.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN
5896809,2006,10,1,7,1330.0,1330,1658.0,1708,CO,162,...,5.0,18.0,0,NaN,0,0.0,0.0,0.0,0.0,0.0
736584,2008,2,14,4,945.0,945,1140.0,1140,YV,2951,...,4.0,17.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN
762312,2007,2,28,3,1114.0,1043,1249.0,1232,YV,7105,...,9.0,15.0,0,NaN,0,17.0,0.0,0.0,0.0,0.0
6665854,2007,11,12,1,1522.0,1529,1805.0,1809,NW,485,...,11.0,9.0,0,NaN,0,0.0,0.0,0.0,0.0,0.0
625369,2006,2,6,1,1015.0,1015,1335.0,1345,WN,2277,...,4.0,9.0,0,NaN,0,0.0,0.0,0.0,0.0,0.0
3221330,2000,7,14,5,1031.0,1035,1249.0,1228,NW,384,...,9.0,46.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN
1335265,2003,3,19,3,2028.0,2005,2206.0,2142,DL,394,...,6.0,20.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN
5697692,2003,11,21,5,2216.0,2215,2252.0,2255,DL,1206,...,4.0,16.0,0,NaN,0,0.0,0.0,0.0,0.0,0.0
1449171,2006,3,1,3,921.0,925,1051.0,1058,FL,475,...,4.0,21.0,0,NaN,0,0.0,0.0,0.0,0.0,0.0
329766,2002,1,9,3,1905.0,1900,2204.0,2212,AA,185,...,6.0,21.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN
4842875,2003,9,24,3,1429.0,1432,1543.0,1601,DH,7865,...,3.0,4.0,0,NaN,0,0.0,0.0,0.0,0.0,0.0
4760884,2004,9,10,5,1229.0,1234,1806.0,1808,UA,1194,...,7.0,13.0,0,NaN,0,0.0,0.0,0.0,0.0,0.0
4676425,2003,9,11,4,2123.0,2125,2225.0,2225,HP,117,...,3.0,12.0,0,NaN,0,0.0,0.0,0.0,0.0,0.0
1065254,2000,3,31,5,2145.0,2110,2142.0,2110,WN,775,...,4.0,3.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN
508156,2004,1,17,6,1140.0,1146,1417.0,1422,AS,492,...,10.0,11.0,0,NaN,0,0.0,0.0,0.0,0.0,0.0

In [23]:
#df_2000_2008.to_csv('df_2000_2008.csv', index = False)